### ISSUE TITLE
Переименовать приложение в simple_collector

### ISSUE THREAD

**Issue by simgislab** [nextgis/simple_collector#1]
Simple collector
Простые учёты

**Comment by NikitaFeodonit** [comment]
Строка из лицензионного заголовка исходных файлов:

Purpose:  Mobile application for WTC data collection.

Как её переделать?

**Comment by NikitaFeodonit** [comment]
Все ресурсы в НГВ имеют ключи:
"wtc_zmucollection", "wtc_zmudata", "wtc_people", "wtc_species", "wtc_tracks", "wtc_routes".

Надо ли их переименовывать?

**Comment by NikitaFeodonit** [comment]
Строка описания приложения в окне "О приложении":

"Mobile application for WTC data collection."
"Мобильное приложение для сбора данных зимних маршрутных учётов."

Как изменить?

**Comment by NikitaFeodonit** [comment]
Нужно ли переименовать сам репозиторий с исходным кодом?

**Comment by simgislab** [comment]
Purpose: Mobile application for simple data collection.
Назначение: Мобильное приложение для сбора данных с помощью простых форм.

О приложении
"Mobile application for simple data collection."
"Мобильное приложение для сбора данных с помощью простых форм."

Ресурсы думаю не будем трогать, пусть останутся пока для истории, потом подумаем.

Реп я переименую
